### ISSUE TITLE
Bateria de Testes

### ISSUE THREAD

**Issue by MilenaNobre** [jjorge98/LicensePlate#6]
Melhoria no chatbot, implementar resposta corretamente
![issues-DF](https://user-images.githubusercontent.com/48803004/85596739-5fc24f80-b620-11ea-99fd-51c542a3f362.jpeg)

**Comment by mariliaalvim** [comment]
![Correção Chatbot](https://user-images.githubusercontent.com/48809314/85598108-a6fd1000-b621-11ea-9e14-d4122ff6f4d8.jpeg)

Resposta corrigida!
